version: '3.8'

services:
  flutter:
    build:
      context: ./prob
      dockerfile: Dockerfile
    image: "${DOCKER_HUB_USERNAME}/flutter-dobu:latest"
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
