version: '3.7'

services:
  flutter-app:
    build:
      context: ./prob   
      dockerfile: Dockerfile 
    container_name: flutter
    volumes:
      - ./prob:/app     
    ports:
      - "8080:80"          
    networks:
      - dobu-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - /home/ubuntu/dobu/nginx.conf:/etc/nginx/nginx.conf:ro # nginx 설정 파일 마운트
    ports:
      - "80:80"         
    networks:
      - dobu-network

networks:
  dobu-network:
    driver: bridge
