name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      # - name: Run docker-compose
      #   uses: hoverkraft-tech/compose-action@v2.0.1
      #   with:
      #     compose-file: "./docker-compose.yml"
      #     action: "build"

      - name: Build and Push Docker image
        run: |
          docker-compose -f docker-compose.yml build --no-cache
          docker-compose -f docker-compose.yml push
          
      # 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master  
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/dobu
            docker-compose -f docker-compose.flutter.yml pull
            docker-compose -f docker-compose.flutter.yml down
            docker-compose -f docker-compose.flutter.yml up -d
            
# - name: Build Docker image
#   run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flutter-dobu:latest ./prob
# - name: Push Docker image
#   run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flutter-dobu:latest

# sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/flutter-dobu:latest
# sudo docker stop flutter1
# sudo docker rm flutter1
# sudo docker run -d -p 8080:80 --name flutter1 ${{ secrets.DOCKER_HUB_USERNAME }}/flutter-dobu:latest
