name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. 저장소 코드 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Flutter 설치
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    # 3. 의존성 설치
    - name: Install dependencies
      run: flutter pub get

    # 4. 코드 분석
    - name: Analyze code
      run: flutter analyze

    # 5. 테스트 실행
    - name: Run tests
      run: flutter test

    # 6. APK 빌드 (선택)
    - name: Build APK
      run: flutter build apk --release
